### ISSUE TITLE
Support for nested symbols?

### ISSUE THREAD

**Issue by ziyafenn** [upxlabs/magic-buttons-sketch-plugin#2]
Hello there. I have a button inside the card and i'd like to apply the magic button to it, but seems to be magic button doesn't work with nested symbols. Or am i doing something wrong?

Thanks.

**Comment by calderaricaio** [comment]
Can you share your context a little more so we can better understand it and try to help you?

**Comment by ziyafenn** [comment]
Here you can see, this card is a symbol. And a red status component it's also a symbol **within** the card.
Each time i run the plugin, it shows the edit box for the text layers of card symbol, but not for the status symbol.

![screenshot 2018-07-27 11 12 33](https://user-images.githubusercontent.com/314302/43312573-fee8f60e-918d-11e8-8ebb-09b3d9d03211.png)

Thanks.

**Comment by calderaricaio** [comment]
Thanks for your example. It's clear now.
So the way we built Magic Buttons it's ready to interact with the symbol you have selected only, it will access the text label and change it and also consider the padding elements inside it to make the resizing.

In this example you have a symbol inside another symbol (nested symbol) that you want to target as a button/resizable element, in this case the red tag (Needs Response). Unfortunately the plugin won't understand it and won't affect the nested symbol, just the card itself which is the one you are selecting right now.
This is the first version of Magic Buttons so our goal was to solve that single and simple task.

It might be possible to achieve something if we manage to upgrade the plugin to do so, but in this case we will need a new version of the code and explore if that's possible because it's a more complex scenario, but we are glad you mentioned it, I will talk with the team see if we can do it in the future but for now the answer is no you can't do it right now, I'm sorry!

Hope we can get an upgrade and make it even better, I can't promise it but who knows?!
